### ISSUE TITLE
Cập nhật Bootstrap và Bootswatch

### ISSUE THREAD

**Issue by abn-volk** [abn-volk/vietloka#1]
Vì Bootstrap và Bootswatch đang trong giai đoạn alpha nên còn nhiều lỗi, phải dùng bản dev để sửa. Đề nghị Huyền vào các trang GitHub của Bootstrap và Bootswatch tải file min.css về cập nhật cho dự án của mình. Cậu không cần tải JS đâu, CSS là đủ nhé :)

**Comment by sieugee** [comment]
Fix với commit 79c2e8c0e6b3c3d2bf32ad29f95b74e7fa58df70
