### ISSUE TITLE
Làm đẹp trang chủ

### ISSUE THREAD

**Issue by abn-volk** [abn-volk/vietloka#2]
Trang chủ hiện giờ quá trống trải, cần có thêm một số hình ảnh tạo hứng thú cho người xem. Có thể lấy hình ảnh một số địa điểm tiêu biểu ở Việt Nam và khi nhấn vào sẽ chuyển đến trang tìm kiếm các địa điểm đó. Trong html thì nó tương đương với việc đặt thuộc tính `(click)` như nút tìm kiếm ở `HomeComponent`, chỉ thay tham số là địa danh (nhớ có dấu nháy đơn).

**Comment by sieugee** [comment]
Commit 0756a539d43e9c8994f4f901ea4fb9ad5d7ea348
