### ISSUE TITLE
Thêm các trang thể hiện đang tải và bị lỗi

### ISSUE THREAD

**Issue by abn-volk** [abn-volk/vietloka#3]
Khi chạy trên `localhost` thì trang web đáp ứng gần như tức thì, nhưng khi chạy trên mạng thì không được như vậy nên cần có các hiệu ứng khi tải trang. Đồng thời, với trang xem một địa điểm homestay (định dạng `house/:id` thì có trường hợp id nhập vào không hợp lệ, cần hiển thị lỗi và đưa link quay lại trang chủ (link này vẫn là `<a>` như bình thường nhưng sẽ sử dụng thuộc tính `routerLink` (tham khảo các link ở navbar để biết thêm chi tiết).

**Comment by sieugee** [comment]
Các trang `house/:id` nếu không hợp lệ sẽ dùng `routerLink` đưa về trang chủ ngay nhưng không hiển thị lỗi
(commit 1ef8b5ea6539f6cbc33e9ee9acf30637f84ae6e9)

**Comment by abn-volk** [comment]
Huyền đã sửa: b734654
