### ISSUE TITLE
Search các nhà ở trong khu vực

### ISSUE THREAD

**Issue by sieugee** [abn-volk/vietloka#4]
Hiện tại mặc dù đã có bản đồ và đã search thành công các khu vực và vị trí và đã có các trang hiển thị thông tin của các nhà trọ cho thuê. Tuy nhiên, bản đồ vẫn chưa hiển thị các vị trí nhà ở trong khu vực để các `guest` chọn và xem

**Comment by sieugee** [comment]
Phần hiển thị các nhà ở đã được giải quyết với commit 82f93ec060761c5a8ac99e2ee2502d6d6bf93404.
Còn phần chọn và xem các `house` nữa

**Comment by abn-volk** [comment]
Người dùng chọn các nhà bằng cách nhấn chuột vào điểm đánh dấu trên bản đồ và xem bằng cách nhấn vào tiêu đề hiện ra.
